Feature/full rewrite
UST-QuAntiL/latex-renderer pull request #5
Opened 2021-05-25 13:18 UTC by mbeisel

Full rewrite finished

2021-05-25 14:42 UTC, buehlefs reviewed
Did not compile for me. I did not test new docker container.

2021-05-25 14:42 UTC, buehlefs commented on src/main/java/com/renderLatex/rest/RenderLatexController.java
> +            e.printStackTrace();
Answer Request with Error Code 400 (or 500)

2021-05-25 14:42 UTC, buehlefs commented on src/main/java/com/renderLatex/rest/RenderLatexController.java
> +                filepath = this.renderService.renderAsPdf(latexContent);
Is it possible to reuse `renderLatexAsPdf` here? This seems like a code duplication.

2021-05-25 14:42 UTC, buehlefs commented on src/main/java/com/renderLatex/rest/RenderLatexController.java
> +        switch (latexContent.getOutput()){
Refactor both switch case statements into the same method.

2021-05-25 14:42 UTC, buehlefs commented on src/main/java/com/renderLatex/utils/Utils.java
> +        filepath = filepath.substring(0, filepath.length() - 15);
```suggestion
        filepath = Paths.get(filepath).getParent().toString();
```

2021-05-25 14:42 UTC, buehlefs commented on src/main/java/com/renderLatex/service/RenderService.java
> +    private final String tempDirectory = Paths.get("").toAbsolutePath().toString()+"/tmp";
```suggestion
    private final String tempDirectory = Paths.get("").toAbsolutePath().resolve("tmp").toString();
```
if the two instance variables are Paths, then all other path manipulation in this module would not have to use string concatenation!

2021-05-25 14:42 UTC, buehlefs commented on src/main/java/com/renderLatex/service/RenderService.java
> +        File file = new File(userDirectory +"/tmp");
```suggestion
        File file = new File(tempDirectory);
```

2021-05-25 14:42 UTC, buehlefs commented on src/main/java/com/renderLatex/service/RenderService.java
> +            FileUtils.deleteDirectory(file);
Add a comment for the rationale behind recreating the temp folder from scratch

2021-05-25 14:42 UTC, buehlefs commented on src/main/java/com/renderLatex/service/RenderService.java
> +        final String currentImagePath = tempDirectory + "/" + uuid;
Do not use string concatenation to build paths if possible.
Also ideally refactor path creation and folder creation into one helper method.

2021-05-25 14:42 UTC, buehlefs commented on src/main/java/com/renderLatex/service/RenderService.java
> +                processBuilderRenderTex.directory(new File(currentImagePath));
move before if-else

2021-05-25 14:42 UTC, buehlefs commented on .gitignore
> +/.idea
also add `tmp` document build folder to gitignore

2021-05-26 14:22 UTC, manuwei commented on README.md
> +The latest version is: **1.1**
as a side comment, we usually prefer to use semantic versioning (x.y.z)_

2021-05-26 14:32 UTC, manuwei requested changes
The code LGTM, I only added a few comments regarding the documentation

Running the tests led to  ``java.lang.Exception: No runnable methods`` - could have a look at that? maybe a @Test annotation or something simliar is missing

2021-05-26 14:32 UTC, manuwei commented on README.md
> +* POST: http://localhost:8082/renderLatex  expects (String content, List<String> latexPackages, String output) as JSON
I think a short example request for each case would be helpful - for example, how to specify multiple packages (for anyone how is not familiar with springboot and what parameters are expected in this case), what params are required

2021-05-26 14:32 UTC, manuwei commented on README.md
> +The latest version is: **1.1**
the last version actually is 1.1.0 - just add the last digit :)

2021-05-27 07:20 UTC, manuwei approved these changes

2021-05-27 07:20 UTC, merged